CREATE TABLE produto ( 
id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_PRODUTO PRIMARY KEY, 
nome VARCHAR(100) NOT NULL, 
descricao VARCHAR(500), 
vl_compra DECIMAL(11,2) NOT NULL, 
vl_venda DECIMAL(11,2) NOT NULL, 
categoria VARCHAR(500), 
dt_cadastro TIMESTAMP NOT NULL);
